services:
  erlang_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_POOL_SIZE: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
