services:
  erlang_app:
    volumes:
      - ./:/app/api_cowboy
      - build:/app/api_cowboy/_build
      - cache:/root/.cache/rebar3
    image: erlang:26
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file: .env
    working_dir: /app/api_cowboy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  build:
  cache:
  
